version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build
          command: docker-compose build
      - run:
          name: Start containers
          command: docker-compose up -d
      - run:
          name: Install dependencies
          command: docker-compose exec service-layer npm i
      - run:
          name: Clear previous coverage outputs
          command: rm -rf .nyc_output/ & rm -rf *.lcov
      - run:
          name: Run tests
          command: docker-compose exec service-layer npm run coverage:test
      - persist_to_workspace:
          root: ~/repo
          paths: .

  publish-coverage:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Publish coverage
          command: npm run coverage:publish

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Login Npm
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish Package
          command: npm publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - publish-coverage:
          requires:
            - test
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/