version: '3'

services:
  service-layer:
    build: .
    container_name: servicelayer
    stdin_open: true
    tty: true
    command: sh

    volumes:
      - .:/src

    depends_on:
      - postgres

  postgres:
    image: postgres:11.2-alpine
    container_name: postgres
    ports:
      - 5432
    environment:
    - POSTGRES_PASSWORD=root
    - POSTGRES_DB=servicelayer